example-app/routes/web.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CounponController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\OrderController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Http\Request;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\CounponController as AdminCounponController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\App;

if (App::environment('production')) {
    URL::forceScheme('https');
}

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route client
Route::get('/', [HomeController::class, 'index'])->name('client.home');


Route::get('product/', [ClientProductController::class, 'index'])->name('client.products.index');
Route::get('product-detail/{id}', [ClientProductController::class, 'show'])->name('client.products.show');

Route::middleware('auth')->group(function(){
    Route::resource('carts', 'Client\CartController');
    Route::post('carts/add', [CartController::class, 'addToCart'])->name('client.carts.add');
    Route::get('/get-image/{size}/{product_id}', 'ProductController@getImage')->name('client.products.get-image');
    Route::get('carts', [CartController::class, 'index'])->name('client.carts.index');
    Route::post('update-quantity-product-in-cart/{cart_product_id}', [CartController::class, 'updateQuantityProduct'])->name('client.carts.update_product_quantity');
    Route::post('remove-product-in-cart/{cart_product_id}', [CartController::class, 'removeProductInCart'])->name('client.carts.remove_product');
    Route::post('apply-coupon', [CartController::class, 'applyCoupon'])->name('client.carts.apply_coupon');
    Route::get('checkout', [CartController::class, 'checkout'])->name('client.checkout.index')->middleware('user.can_checkout_cart');
    Route::post('process-checkout', [CartController::class, 'processCheckout'])->name('client.checkout.proccess')->middleware('user.can_checkout_cart');
    Route::get('list-orders', [OrderController::class, 'index'])->name('client.orders.index');
    Route::post('orders/cancel/{id}', [OrderController::class, 'cancel'])->name('client.orders.cancel');
});

// Route::resource('coupons', 'Admin\CouponController');
Auth::routes();
Route::middleware('auth')->group(function(){
    Route::resource('coupons', 'Admin\CouponController');
    Route::get('coupons', [AdminCounponController::class, 'index'])->name('coupons.index');
    Route::get('/coupons/create', [AdminCounponController::class, 'index'])->name('coupons.create');
});


Route::middleware('auth')->group(function(){
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('roles', AdminRoleController::class);
    Route::get('roles/{role}', [AdminRoleController::class, 'show'])->name('roles.show');
    Route::get('roles/{role}/edit', [AdminRoleController::class, 'edit'])->name('roles.edit');
    Route::get('/roles/search', [AdminRoleController::class, 'search'])->name('roles.search');
    Route::delete('roles/{id}', [AdminRoleController::class, 'destroy'])->name('roles.destroy');

    Route::resource('users', AdminUserController::class);
    Route::get('users/{id}/show', [AdminUserController::class, 'show'])->name('users.show');
    Route::get('/users/search', [AdminUserController::class, 'search'])->name('users.search');


    Route::resource('categories', AdminCategoryController::class);

    Route::resource('products', AdminProductController::class);
    Route::get('/products', [AdminProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [AdminProductController::class, 'create'])->name('admin.products.create');
    Route::get('products/{product}/edit', [AdminProductController::class, 'edit'])->name('admin.products.edit');
    Route::get('products/{product}', [AdminProductController::class, 'show'])->name('admin.products.show');
    Route::delete('/products/{id}', [AdminProductController::class, 'destroy'])->name('admin.products.destroy');
    Route::put('/products/{id}', [AdminProductController::class, 'update'])->name('admin.products.update');

    Route::get('orders', [AdminOrderController::class, 'index'])->name('admin.orders.index');

    Route::get('product/search/', [ClientProductController::class, 'search'])->name('client.products.search');

    //   Route::resource('roles', RoleController::class);
    //   Route::prefix('roles')->controller(RoleController::class)->name('roles.')->group(function(){
    //     Route::get('/', 'index')->name('index')->middleware('role:super-admin');
    //     Route::post('/', 'store')->name('store')->middleware('role:super-admin');
    //     Route::get('/create', 'create')->name('create')->middleware('role:super-admin');
    //     Route::get('/{coupon}', 'show')->name('show')->middleware('role:super-admin');
    //     Route::put('/{coupon}', 'update')->name('update')->middleware('role:super-admin');
    //     Route::get('/{role}', 'show')->name('show')->middleware('role:super-admin');
    //     Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('role:super-admin');
    //     Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('role:super-admin');
    // });
    // Route::resource('users', UserController::class);
    // Route::prefix('users')->controller(UserController::class)->name('users.')->group(function(){
    //     Route::get('/', 'index')->name('index')->middleware('permission:show-user');
    //     Route::post('/', 'store')->name('store');
    //     Route::get('/create', 'create')->name('create')->middleware('permission:create-user');
    //     Route::get('/{user}', 'show')->name('show')->middleware('permission:show-user');
    //     Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-user');
    //     Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-user');
    //     Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-user');
    //     Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-user');
    // });
    // Route::resource('categories', CategoryController::class);
    // Route::prefix('categories')->controller(CategoryController::class)->name('categories.')->group(function(){
    //     Route::get('/', 'index')->name('index')->middleware('permission:show-category');
    //     Route::post('/', 'store')->name('store')->middleware('permission:create-category');
    //     Route::get('/create', 'create')->name('create')->middleware('permission:create-category');
    //     Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-category');
    //     Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-category');
    //     Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-category');
    //     Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-category');
    // });

    // Route::resource('products', ProductController::class);

    // Route::prefix('products')->controller(ProductController::class)->name('products.')->group(function(){
    //     Route::get('/', 'index')->name('index')->middleware('permission:show-product');
    //     Route::post('/', 'store')->name('store')->middleware('permission:create-product');
    //     Route::get('/create', 'create')->name('create')->middleware('permission:create-product');
    //     Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-product');
    //     Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-product');
    //     Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-product');
    //     Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-product');
    // });
    // Route::prefix('coupons')->controller(CounponController::class)->name('coupons.')->group(function(){
        // Route::get('/', 'index')->name('index')->middleware('permission:show-coupon');
        // Route::post('/', 'store')->name('store')->middleware('permission:create-coupon');
        // Route::get('/create', 'create')->name('create')->middleware('permission:create-coupon');
        // Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-coupon');
        // Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-coupon');
        // Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-coupon');
        // Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-coupon');
    // });    
    Route::post('update-status/{id}', [AdminOrderController::class, 'updateStatus'])->name('admin.orders.update_status')->middleware('list-order');
});

example-app/app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Role as ModelsRole;
use Illuminate\Database\Eloquent\Casts\Attribute;
use App\Traits\HandleImage;
use App\Models\Permission;
class Role extends ModelsRole
{
    use HasFactory,HandleImage;

    protected $fillable = [
        'role_id',
        'name',
        'display_name',
        'group',
        'guard_name'
    ];
    public function details()
    {
        return $this->hasOne('App\Models\Detail');
    }
    public function categories()
    {
        return $this->hasOne('App\Models\Detail');
    }
    public function permission()
    {
        return $this->belongsToMany('App\Models\Permission');
    }
}

example-app/app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Roles\CreateRoleRequest;
use App\Http\Requests\Roles\UpdateRoleRequest;
use App\Models\Permission;
use App\Models\Role;
use App\Services\RoleService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class RoleController extends Controller
{
    protected RoleService $roleService;

    /**
     * @param RoleService $roleService
     */
    public function __construct(RoleService $roleService)
    {
        $this->roleService = $roleService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(Request $request): Application|Factory|View
    {
        $search = $request->query('search');
        $roles = $this->roleService->getWithPaginate($search);
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): View|Factory|Application
    {
        $permissions = Permission::all()->groupBy('group');
        return view('admin.roles.create', compact('permissions'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRoleRequest $request
     * @return RedirectResponse
     */
    public function store(CreateRoleRequest $request): RedirectResponse
    {
        $this->roleService->create($request);
        return redirect()->route('roles.index')->with(['message' => 'create success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function show($id): Application|Factory|View
    {
        // Assuming $this->roleService->findOrFail() retrieves the role by its ID
        $role = $this->roleService->findOrFail($id);

        return view('admin.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function edit($id): View|Factory|Application
    {
        $role = $this->roleService->findOrFail($id);
        $permissions = Permission::all()->groupBy('group');
        return view('admin.roles.edit', compact('role', 'permissions'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRoleRequestuest $req
     * @param int $id
     * @return RedirectResponse
     */
    public function update(UpdateRoleRequest $request, $id): RedirectResponse
    {
        $this->roleService->update($request, $id);
        return redirect()->route('roles.index')->with(['message' => 'update success']);
    }

     
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy($id): RedirectResponse
    {
        $this->roleService->delete($id);
        return redirect()->route('roles.index')->with(['message' => 'delete success']);
    }

}

example-app/resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create Roles')
@section('content')
    <div class="card">
        <h1>Create role</h1>

        <div>
            <form id="createRoleForm" action="{{ route('roles.store') }}" method="post">
                @csrf

                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') }}" name="name" class="form-control">
                    @error('name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Display Name</label>
                    <input type="text" value="{{ old('display_name') }}" name="display_name" class="form-control">
                    @error('display_name')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label name="group" class="ms-0">Group</label>
                    <select name="group" class="form-control">
                        <option value="system">System</option>
                        <option value="user">User</option>
                    </select>
                    @error('group')
                        <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="">Permission</label>
                    <div class="row">
                        @foreach ($permissions as $groupName => $permission)
                            <div class="col-5">
                                <h4>{{ $groupName }}</h4>
                                <div>
                                    @foreach ($permission as $item)
                                        <div class="form-check">
                                            <input class="form-check-input" name="permission_ids[]" type="checkbox"
                                                value="{{ $item->id }}">
                                            <label class="custom-control-label"
                                                for="customCheck1">{{ $item->display_name }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>

                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#createRoleForm').submit(function(event) {
                event.preventDefault();
                var formData = new FormData(this);

                // Ensure permission_ids key exists
                if (!$("input[name='permission_ids[]']").is(":checked")) {
                    alert("Please select at least one permission.");
                    return false;
                }

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function(response) {
                        alert('Role created successfully.');
                        window.location.href = "{{ route('roles.index') }}";
                    },
                    error: function(xhr, status, error) {
                        var errorMessage = xhr.status + ': ' + xhr.statusText;
                        alert('Error - ' + errorMessage);
                    }
                });
            });
        });

    </script>
@endsection

example-app/resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Edit Roles ' . $role->name)
@section('content')
    <div class="card">
        <h1>Edit role</h1>

        <div>
            <form id="editRoleForm" action="{{ route('roles.update', $role->id) }}" method="post">
                @csrf
                @method('PUT')

                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') ?? $role->name }}" name="name" class="form-control">
                    <span class="text-danger" id="name_error"></span> <!-- Error message placeholder -->
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Display Name</label>
                    <input type="text" value="{{ old('display_name') ?? $role->display_name }}" name="display_name" class="form-control">
                    <span class="text-danger" id="display_name_error"></span> <!-- Error message placeholder -->
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Group</label>
                    <select name="group" class="form-control">
                        <option value="system" {{ $role->group === 'system' ? 'selected' : '' }}>System</option>
                        <option value="user" {{ $role->group === 'user' ? 'selected' : '' }}>User</option>
                    </select>
                    <span class="text-danger" id="group_error"></span> <!-- Error message placeholder -->
                </div>

                <div class="form-group">
                    <label for="">Permission</label>
                    <div class="row">
                        @foreach ($permissions as $groupName => $permission)
                            <div class="col-5">
                                <h4>{{ $groupName }}</h4>
                                <div>
                                    @foreach ($permission as $item)
                                        <div class="form-check">
                                            <input class="form-check-input" name="permission_ids[]" type="checkbox" {{ $role->permissions->contains('name', $item->name) ? 'checked' : '' }} value="{{ $item->id }}">
                                            <label class="custom-control-label" for="customCheck1">{{ $item->display_name }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>

                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#editRoleForm').on('submit', function(event) {
                event.preventDefault();

                $.ajax({
                    url: $(this).attr('action'),
                    type: 'POST',
                    data: $(this).serialize(),
                    success: function(response) {
                        alert('Role edited successfully.');
                        window.location.href = "{{ route('roles.index') }}";
                    },
                    error: function(xhr, textStatus, errorThrown) {
                        // Handle error response
                        if (xhr.status == 422) {
                            var errors = xhr.responseJSON.errors;
                            $.each(errors, function(key, value) {
                                $('#' + key + '_error').html('<span class="text-danger">' + value[0] + '</span>');
                            });
                        } else if (xhr.status == 500) {
                            var errorMessage = xhr.responseJSON.message;
                            alert(errorMessage);
                        } else {
                            alert('An unexpected error occurred. Please try again.');
                        }
                    }
                });
            });
        });
    </script>
@endsection

example-app/resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Roles')
@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">

<div class="card">
    @if (session('message'))
        <h1 class="text-primary">{{ session('message') }}</h1>
    @endif

    <h1>Role list</h1>
    <div>
            <a href="{{ route('roles.create') }}" class="btn btn-primary">Create</a>
            <form action="{{ route('roles.index') }}" method="GET">
                <div class="form-group">
                    <label for="search">Search:</label>
                    <input type="text" name="search" id="search" class="form-control" placeholder="Enter search ">
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Display Name</th>
                <th>Action</th>
            </tr>
            @foreach ($roles as $role)
                <tr id="role_{{ $role->id }}">
                    <td>{{ $role->id }}</td>
                    <td>{{ $role->name }}</td>
                    <td>{{ $role->display_name }}</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-warning">Edit</a>
                            <button class="btn btn-delete btn-danger" data-id="{{ $role->id }}">Delete</button>
                        </div>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
    {{ $roles->appends(request()->except('page'))->links() }}
</div>
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this role?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="cancelDelete">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
$(document).ready(function () {
    // Handle delete button click
    $('.btn-delete').click(function () {
        var roleId = $(this).data('id');
        $('#confirmDelete').data('id', roleId); // Set roleId as data-id for confirmDelete button
        $('#deleteConfirmationModal').modal('show');
    });

    // Handle confirm delete
    $('#confirmDelete').click(function () {
        var roleId = $(this).data('id'); // Get roleId from data-id
        $.ajax({
            url: '/roles/' + roleId,
            type: 'DELETE',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            success: function (response) {
                $('#deleteConfirmationModal').modal('hide');
                $('#role_' + roleId).remove();
                alert('Role deleted successfully.');
            },
            error: function (xhr) {
                console.error(xhr.responseText);
                window.location.reload(); 
            }
        });
    });

    // Handle cancel delete
    $('#cancelDelete').click(function () {
        $('#deleteConfirmationModal').modal('hide');
        });
    });
</script>
@endsection

example-app/resources/views/admin/roles/search.blade.php
@extends('admin.layouts.app')

@section('title', 'Search Roles')

@section('content')
    <div class="card">
        <h1>Search Roles</h1>

        <form action="{{ route('roles.search') }}" method="GET">
            <div class="form-group">
                <label for="search">Search:</label>
                <input type="text" name="search" id="search" class="form-control" placeholder="Enter search">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>
@endsection